kind: pipeline
name: default

steps:
- name: Build
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - make -C src all

- name: Test
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - make -C src test

- name: Static Analysis
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - cppcheck --enable=warning --quiet src

- name: Valgrind
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - make -C src valgrind
