kind: pipeline
name: default

steps:
- name: Build (Clang)
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - export CC=/usr/bin/clang
  - export CXX=/usr/bin/clang++
  - $CC --version
  - cmake -B build/clang -DCMAKE_CXX_COMPILER="$CXX" -G "Ninja" .
  - cmake --build build/clang
  - valgrind ./build/clang/src/CPPTimerPool

- name: Build (GCC)
  image: abcminiuser/docker-ci-ubuntu-buildtools
  commands:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - $CC --version
  - cmake -B build/gcc -DCMAKE_CXX_COMPILER="$CXX" -G "Ninja" .
  - cmake --build build/gcc
  - valgrind ./build/gcc/src/CPPTimerPool
